# Generated by Django 4.1.1 on 2022-09-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playstation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prem',
            name='age',
        ),
        migrations.RemoveField(
            model_name='prem',
            name='gender',
        ),
        migrations.AddField(
            model_name='prem',
            name='lastname',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
