# Generated by Django 4.1.1 on 2022-10-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playstation', '0003_prem_ph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prem',
            old_name='name',
            new_name='firstname',
        ),
    ]
